### ISSUE TITLE
Query batching?

### ISSUE THREAD

**Issue by Kurren123** [fsprojects/FSharp.Data.GraphQL#104]
Hi

Is it possible to batch queries? So if I am returning 100 `people` with their `addresses`, I don't want to query the database 100 times but instead run a single query that has a `join`?

Thanks

**Comment by Horusiath** [comment]
Hi @Kurren123 .

FSharp.Data.GraphQL comes with something called property tracker. It allows you to perform runtime query analysis in order to detect fields and properties that may be potentially used when resolving your GraphQL query. It may be used to prefetch all of the necessary data up-front in the top-level resolver. [Here](http://fsprojects.github.io/FSharp.Data.GraphQL/linq.html) is the example of such thing.

Downside is that this feature relies on F# quotation expressions and reflected definitions, so it cannot track properties outside expression tree boundaries.

**Comment by Kurren123** [comment]
Perfect, thank you

**Comment by Kurren123** [comment]
Hi @Horusiath. Thank you for your earlier reply. I'm still trying to wrap my head around this tracker stuff. For the LINQ example in the page that you gave me, the resolver for "people" is this:

`fun ctx () ->  peopleList.AsQueryable().Apply(ctx.ExecutionInfo, ctx.Variables) |> Seq.toList) ]`

However I'm not sure what the "Apply" method does. I tried googling in case it was a linq method but I can't find it anywhere. Any help would be much appreciated.

Thanks in advanced,
Kurren

**Comment by Horusiath** [comment]
@Kurren123 [Apply](https://github.com/fsprojects/FSharp.Data.GraphQL/blob/dev/src/FSharp.Data.GraphQL.Server/Linq.fs#L619) is an extension method. Be aware, that it's has some limitations (i.e. may lost track on abstract graphql types).

**Comment by johnberzy-bazinga** [comment]
Closing as this appears to be an old issue.
